title:              "demo"
email:              "matteo@pedani.it" 
description:        "demo pedani it"
author:             "Matteo Pedani"
baseurl:            "/"
url:                ""
permalink: /:slug/
logo: "/images/cropped-scritture_logo-1.jpg"

looptime: 5

# Social Profiles
twitter_username:   "matteopedani"
github_username:    
facebook_username:  "matteo.pedani"
linkedin_username:  "matteopedani/"

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           
paginate_path:      "/posts/page:num/"
plugins: 
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
exclude: [".jekyll-cache", "Gemfile", "Gemfile.lock", "type-on-strap.gemspec", "*.gem", ".idea", "vendor/*",
  "LICENSE", "README.md", "screenshot.png", "assets/package.json", "assets/node_modules", "assets/gulpfile.js", "bin/cbuild"]


lang:
    default: it
    posted_by: di
    previus_post: "articolo precedente"
    next_post: "aricolo successivo"
    previus: "precedente"
    next: "successivo"
    post: "articolo"
    all_posts: "tutti gli articoli"
    read: "leggi"
    enter_keywords: "cerca le parole"


menu:
  - 1:
     - name: "contatti"
     - link: "/contatti/"
  - 2:
     - name: "chi siamo"
     - link: "/chi/"
  - 3:
     - name: "dove siamo"
     - link: "/dove_siamo/"
  - 3:
     - name: "acquista"
     - link: "/acquista/"

     
collection:
  credits:
    output: true
    permalink: /credits/:path/


